version: "3.9"
services:

  # Development service
  dev:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install && npm run dev -- --host 0.0.0.0"

  # Production build + serve
  web:
    build:
      context: .
      target: builder
    image: webapp_
    container_name: webapp_
    # intermediate build only—no ports

  prod:
    image: nginx:stable-alpine
    depends_on:
      - web
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    command: ["nginx", "-g", "daemon off;"]
